### ISSUE TITLE
Config provider

### ISSUE THREAD

**Issue by SquaredPotato** [smartknob-ha/sdk#21]
We're going to need a generic way to store dynamic things in non-volatile memory sooner rather than later. 
There's a few libraries provided by the ESP-IDF that will be of help:
 - https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/index.html

Since we're planning to use JSON for the settings, such as calibration values, WiFi settings etc, a binary storage option would be most useful.
For things that are tightly coupled to the firmware version, it might be most practical to be able to embed those in the firmware, and just provide a neat way to retrieve them. Mostly useful for the website that we might one day make.

For things that fall in-between, access to normal NVS blocks could be handy.

An important thing to keep in mind that is best handled here, is A/B partitioning. It's a really bad user experience if suddenly the WiFi password is lost due to corruption.
If we're going to implement live backup and restore anywhere, I reckon this is the best layer to do so.

**Comment by abrondijk** [comment]
After some debate, we came to the following idea:

A generic `ConfigProvider` class, that wraps around the [NVS C++ handle](https://github.com/espressif/esp-idf/blob/v5.1.3/examples/storage/nvs_rw_value_cxx/main/nvs_value_example_main.cpp), like so:

```c++
class Config {
  template<typename T>
  esp_err_t loadFromStorage(const char* key, T& object) {
    return nvs.get_blob(key, *object);
  };
  esp_err_t saveToStorage(const char* key, T& object) {
    return nvs.set_blob(key, *object);
  };
}
```

Each component that requires settings, should implement the following:

- A struct that contains all settings
- [`nlohmann::json` arbitrary types conversion](https://json.nlohmann.me/features/arbitrary_types/) on said config struct, in order to (de)serialize said config struct to/from json, for a future webserver component
- A constructor that takes a reference of `ConfigProvider`
- A `setConfig` method that takes said config struct as parameter. This method should:
  - Save the new settings internally
  - Save the incoming settings to storage, through `ConfigProvider`
  - If applicable, set the component status to `RESTART_REQUIRED`, indicating to the component manager that it should be restarted in order apply new settings
  - If applicable, set the component status to `REBOOT_REQUIRED`, indicating that the device has to be rebooted in order to apply new settings
- Loading settings from storage through `ConfigProvider`
  - This should be done either in the constructor or in `initialize`
  - If there are no settings retrievable through `ConfigProvider` (e.g. the device boots for the first time), default settings should be loaded ***and*** saved through `ConfigProvider`
